language: node_js
node_js:
  - "node"
  - "lts/*"
before_script:
  npm install istanbul -g && npm install coveralls --no-save && npm run compile
after_script:
  NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha index.test.js --report lcovonly -x index.test.js -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
